#!/usr/bin/env bash

curl -X 'POST' 'https://hackage.haskell.org/packages/uploaders/' \
  -H "Authorization: X-ApiKey $HACKAGE_API_KEY" \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -d "user=$1"
